import { useEffect, useState, type FormEvent } from "react";
import { Edit3, Music2, Plus, Search, Trash2, X } from "lucide-react";
import { ConfirmModal, EmptyState, Modal, ModernSelect, PageHeader } from "../components/ui";
import { endpoints } from "../lib/api";
import type { Cue, Song, SongSection } from "../types";
import { useToast } from "../contexts/AppContexts";

const section = (order = 1): SongSection => ({ id: "", songId: "", sectionLabel: order === 1 ? "Verse 1" : "Chorus", lyrics: "", displayOrder: order });
const blank = (): Song => ({ id: "", title: "", artist: "", defaultKey: "C", bpm: 120, sections: [section()] });

export function Songs() {
  const { show } = useToast();
  const [songs, setSongs] = useState<Song[]>([]); const [cues, setCues] = useState<Cue[]>([]); const [search, setSearch] = useState(""); const [edit, setEdit] = useState<Song | null>(null); const [remove, setRemove] = useState<Song | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); endpoints.songs(search).then(data => setSongs(data || [])).catch(e => { setSongs([]); show(e instanceof Error ? e.message : "Failed to load songs", "error"); }).finally(() => setLoading(false)); }, 250); return () => window.clearTimeout(timer); }, [search, show]);
  useEffect(() => { endpoints.cues().then(data => setCues((data || []).filter(cue => cue.active))).catch(e => show(e instanceof Error ? e.message : "Failed to load cue presets", "error")); }, [show]);
  const sectionOptions = [...new Set(cues.map(cue => cue.label).filter(Boolean))];
  const addSection = () => setEdit(current => current ? { ...current, sections: [...current.sections, { ...section(current.sections.length + 1), sectionLabel: sectionOptions[0] || "Verse" }] } : current);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!edit) return; try { const base = { title: edit.title.trim(), artist: edit.artist.trim(), defaultKey: edit.defaultKey.trim(), bpm: edit.bpm }; const sections = edit.sections.map((s, i) => ({ ...(s.id ? { id: s.id } : {}), sectionLabel: s.sectionLabel.trim(), lyrics: s.lyrics.trim(), displayOrder: i + 1 })); const saved = edit.id ? await endpoints.updateSong({ id: edit.id, ...base, sections }) : await endpoints.createSong({ ...base, sections: sections.map(({ sectionLabel, lyrics, displayOrder }) => ({ sectionLabel, lyrics, displayOrder })) }); setSongs(current => edit.id ? current.map(x => x.id === saved.id ? saved : x) : [...current, saved].sort((a,b) => a.title.localeCompare(b.title))); setEdit(null); show("Song saved"); } catch(e) { show(e instanceof Error ? e.message : "Failed to save song", "error"); } };
  const updateSection = (index: number, field: "sectionLabel" | "lyrics", value: string) => setEdit(current => current ? ({ ...current, sections: current.sections.map((s,i) => i === index ? { ...s, [field]: value } : s) }) : current);
  return <>
    <PageHeader title="Songs" description="Manage songs and lyric sections used by Cue Control." action={<button className="btn-primary" onClick={() => { const next = blank(); next.sections[0].sectionLabel = sectionOptions[0] || next.sections[0].sectionLabel; setEdit(next); }}><Plus size={18}/> Add song</button>}/>
    <label className="relative mb-5 block max-w-xl"><Search className="absolute left-4 top-3.5 muted" size={18}/><input className="field !pl-11" placeholder="Search title or artist..." value={search} onChange={e => setSearch(e.target.value)}/></label>
    {!loading && !songs.length ? <EmptyState title="No songs yet" description="Add the first song and organize its lyric sections."/> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{songs.map(song => <article className="surface p-5" key={song.id}><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-brand-500/10 text-brand-500"><Music2 size={20}/></span><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{song.title}</h2><p className="text-sm muted">{song.artist}</p></div></div><div className="my-4 flex gap-2 text-xs"><span className="chip bg-slate-100 dark:bg-slate-900">Key {song.defaultKey}</span><span className="chip bg-slate-100 dark:bg-slate-900">{song.sections?.length || 0} sections</span></div><div className="flex gap-2"><button className="btn-secondary flex-1" onClick={() => setEdit(structuredClone({ ...song, sections: song.sections || [] }))}><Edit3 size={16}/> Edit</button><button className="btn-secondary text-red-500" onClick={() => setRemove(song)}><Trash2 size={16}/></button></div></article>)}</div>}
    <Modal open={!!edit} title={edit?.id ? "Edit song" : "Add song"} onClose={() => setEdit(null)}>{edit && <form className="max-h-[75vh] space-y-4 overflow-y-auto pr-1" onSubmit={save}><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">Title</span><input className="field" required value={edit.title} onChange={e => setEdit({...edit,title:e.target.value})}/></label><label><span className="label">Artist</span><input className="field" required value={edit.artist} onChange={e => setEdit({...edit,artist:e.target.value})}/></label><label><span className="label">Default Key</span><input className="field" required value={edit.defaultKey} onChange={e => setEdit({...edit,defaultKey:e.target.value})}/></label></div><div className="flex items-center justify-between"><h3 className="font-bold">Lyrics sections</h3><button type="button" className="btn-secondary !min-h-9 text-sm" disabled={!sectionOptions.length} onClick={addSection}><Plus size={15}/> Section</button></div>{!sectionOptions.length && <p className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-500">Create a Cue Preset first before adding lyric sections.</p>}{edit.sections.map((s,i) => <div className="rounded-xl border p-3" key={`${s.id}-${i}`}><div className="mb-2 flex gap-2"><ModernSelect className="flex-1" ariaLabel="Lyrics section cue" options={[...new Set([s.sectionLabel, ...sectionOptions])].filter(Boolean).map(value => ({ value }))} value={s.sectionLabel} onValueChange={value => updateSection(i,"sectionLabel",value)}/><button type="button" className="btn-secondary text-red-500" disabled={edit.sections.length===1} onClick={() => setEdit({...edit,sections:edit.sections.filter((_,x)=>x!==i)})}><X size={16}/></button></div><textarea className="field min-h-32 resize-y" required placeholder="Lyrics..." value={s.lyrics} onChange={e => updateSection(i,"lyrics",e.target.value)}/></div>)}<button className="btn-primary w-full" disabled={!edit.sections.length || !sectionOptions.length}>Save song</button></form>}</Modal>
    <ConfirmModal open={!!remove} title="Delete song?" description={`Delete ${remove?.title || "this song"} and all lyric sections?`} onClose={() => setRemove(null)} onConfirm={async()=>{if(!remove)return;try{await endpoints.deleteSong(remove.id);setSongs(x=>x.filter(s=>s.id!==remove.id));setRemove(null);show("Song deleted","warning");}catch(e){show(e instanceof Error?e.message:"Failed to delete song","error");}}}/>
  </>;
}
